targets:
  $default:
    dependencies:
      - :payloads_target
      - :models_target

    builders:
      source_gen|combining_builder:
        options:
          preamble: |
            // Ignore warnings for generated code.
            // ignore_for_file: type=warning
            // ignore_for_file: type=lint
            // coverage:ignore-file

      freezed:
        options:
          format: false
          map: false
          when:
            when: false
            maybe_when: false
            when_or_null: false
        generate_for:
          - lib/features/*/domain/entities/*.dart
          - lib/features/*/presentation/blocs/*_bloc.dart
          - lib/features/*/presentation/blocs/*/*_bloc.dart
          - lib/features/*/presentation/blocs/*_cubit.dart
          - lib/features/*/presentation/blocs/*/*_cubit.dart

      json_serializable:
        enabled: false

      retrofit_generator:
        generate_for:
          - lib/features/*/data/datasources/*_api_client.dart

      injectable_generator:injectable_builder:
        generate_for:
          - lib/di/injection_register_module.dart
          - lib/core/network/network_module.dart
          - lib/core/firebase/firebase_auth_interceptor.dart
          - lib/features/*/data/datasources/*_api_client.dart
          - lib/features/*/data/datasources/*_data_source_impl.dart
          - lib/features/*/data/repositories/*_repository_impl.dart
          - lib/features/*/domain/usecases/*.dart
          - lib/features/*/presentation/blocs/*_bloc.dart
          - lib/features/*/presentation/blocs/*/*_bloc.dart
          - lib/features/*/presentation/blocs/*_cubit.dart
          - lib/features/*/presentation/blocs/*/*_cubit.dart

      injectable_generator:injectable_config_builder:
        generate_for:
          - lib/di/injection.dart

      envied_generator:envied:
        generate_for:
          - lib/core/app_config/env/*.dart

      hive_ce_generator:hive_type_adapter_generator:
        generate_for:
          - lib/features/quick_split/data/models/quick_split_hive_registerer.dart

      hive_ce_generator:hive_adapters_generator:
        generate_for:
          - lib/features/quick_split/data/models/quick_split_hive_registerer.dart

      hive_ce_generator:hive_registrar_intermediate_generator:
        generate_for:
          - lib/features/quick_split/data/models/quick_split_hive_registerer.dart

  payloads_target:
    sources:
      - lib/features/*/data/models/*_payload.dart
    builders:
      json_serializable:
        options:
          create_factory: false
          create_to_json: true
          explicit_to_json: true
      source_gen|combining_builder:
        enabled: false

  models_target:
    sources:
      - lib/features/*/data/models/*_model.dart
    builders:
      json_serializable:
        options:
          create_factory: true
          create_to_json: false
          explicit_to_json: false
      source_gen|combining_builder:
        enabled: false
