import 'package:sky_storage_isar/sky_storage_isar.dart';

part 'outbox_action_isar_model.g.dart';

/// Status values for outbox queue entries.
enum OutboxStatus {
  pending,
  inFlight,
  failed,
}

@collection
class OutboxActionIsarModel {
  Id isarId = Isar.autoIncrement;

  /// Temporary client-side UUID assigned before server confirms the real ID.
  @Index(unique: true)
  late String idempotencyKey;

  /// The action type (e.g. 'create_expense', 'delete_group').
  late String actionType;

  /// JSON-encoded mutation payload.
  late String payloadJson;

  /// Temporary ID generated by the client (null for non-create actions).
  String? tempId;

  /// Server-assigned ID once the action has been flushed (null until then).
  String? serverId;

  @enumerated
  OutboxStatus status = OutboxStatus.pending;

  int retryCount = 0;
  DateTime? lastAttemptedAt;

  @Index()
  DateTime createdAt = DateTime.now();
}
